from typing import Any, Dict
from crewai import Agent, Crew, Process, Task
from crewai.task import TaskOutput
from crewai.project import CrewBase, agent, crew, task
from tools.custom_tool import search_tool
from langchain_core.callbacks import BaseCallbackHandler
import streamlit as st

# Uncomment the following line to use an example of a custom tool

# Check our tools documentations for more information on how to use them
# from crewai_tools import SerperDevTool

def step_callback(output):
	"""Example of a step callback function"""
	text_agent = 'Pesquida finalizada' if 'Interpretador' else 'Mapa mental finalizado'
	with st.status(text_agent):
		raw = f'{output.agent}: {output.raw}'
		st.session_state.messages.append({"role": "assistant", "content": raw})
		st.chat_message("assistant").markdown(raw)

class CustomHandler(BaseCallbackHandler):
    """A custom handler for logging interactions within the process chain."""
    
    def __init__(self, agent_name: str):
        super().__init__()
        self.agent_name = agent_name

    def on_chain_start(self, serialized: Dict[str, Any], outputs: Dict[str, Any], **kwargs: Any):
        """Log the start of a chain with user input."""
        st.session_state.messages.append({"role": "assistant", "content": outputs['input']})
        st.chat_message("assistant").markdown(outputs['input'])

    def on_agent_action(self, serialized: Dict[str, Any], inputs: Dict[str, Any], **kwargs: Any):
        """Log the action taken by an agent during a chain run."""
        st.session_state.messages.append({"role": "assistant", "content": inputs['input']})
        st.chat_message("assistant").markdown(inputs['input'])

    def on_chain_end(self, outputs: Dict[str, Any], **kwargs: Any):
        """Log the end of a chain with the output generated by an agent."""
        st.session_state.messages.append({"role": self.agent_name, "content": outputs['output']})
        st.chat_message(self.agent_name).markdown(outputs['output'])

@CrewBase
class ObsidianMindmapCrew():
	"""TaianeViagens crew"""

	@agent
	def interpretador(self) -> Agent:
		return Agent(
			config=self.agents_config['interpretador'],
			verbose=True,
		)

	@agent
	def criador(self) -> Agent:
		return Agent(
			config=self.agents_config['criador'],
			verbose=True,
			
		)
  
	@agent
	def validador(self) -> Agent:
		return Agent(
			config=self.agents_config['validador'],
			verbose=True,
		)
		

	@task
	def pesquisar(self) -> Task:
		return Task(
			config=self.tasks_config['interpretar_task'],
   			callback=step_callback
		)

	@task
	def resumir(self) -> Task:
		return Task(
			config=self.tasks_config['criar_task'],
   			callback=step_callback
		)
  

	@task
	def validar(self) -> Task:
		return Task(
			config=self.tasks_config['validar_task'],
   			callback=step_callback
		)
  

	@crew
	def crew(self) -> Crew:
		"""Creates the TaianeViagens crew"""
		return Crew(
			agents=self.agents, # Automatically created by the @agent decorator
			tasks=self.tasks, # Automatically created by the @task decorator
			process=Process.hierarchical,
			manager_agent=Agent(
				role="manager",
				goal="Gerar um JSON para mapa mental no modelo do obsidian",
				backstory="""
				O objetivo deste projeto é gerar um mapa mental de um texto fornecido pelo usuário.
				Para isso, utilizaremos uma abordagem hierárquica, onde cada agente será responsável por uma etapa do processo.
				Os agentes envolvidos são: interpretador, criador e validador.
				O interpretador será responsável por interpretar o texto fornecido pelo usuário e extrair as informações relevantes.
				O criador será responsável por criar o mapa mental a partir das informações interpretadas.
				O validador será responsável por validar o mapa mental gerado.
				Seu objetivo é garantir que o mapa mental gerado seja de qualidade e atenda às expectativas do usuário.
    
				Devolva para o usuário o JSON correto, mas garanta que o JSON gerado pelo Criador foi VALIDADO pelo Validador
    			""",
       			verbose=True,
			),
			verbose=True,
			language='pt-br',
			memory=True,
			
			# process=Process.hierarchical, # In case you wanna use that instead https://docs.crewai.com/how-to/Hierarchical/
		)