from typing import Any, Dict
from crewai import Agent, Crew, Process, Task
from crewai.task import TaskOutput
from crewai.project import CrewBase, agent, crew, task
from tools.custom_tool import search_tool
from langchain_core.callbacks import BaseCallbackHandler
import streamlit as st

# Uncomment the following line to use an example of a custom tool

# Check our tools documentations for more information on how to use them
# from crewai_tools import SerperDevTool

def step_callback(output):
	"""Example of a step callback function"""
	texts = {
		"gerar_domain": "DOMAIN",
		"gerar_configuration": "CONFIGURATION",
		"gerar_dto": "DTO",
		"gerar_service": "SERVICE",
		"gerar_commands": "COMMANDS",
	}
	with st.status(texts[output.name]):
		raw = output.raw
		st.session_state.messages.append({"role": "assistant", "content": raw})
		st.chat_message("assistant").markdown(raw)

class CustomHandler(BaseCallbackHandler):
    """A custom handler for logging interactions within the process chain."""
    
    def __init__(self, agent_name: str):
        super().__init__()
        self.agent_name = agent_name

    def on_chain_start(self, serialized: Dict[str, Any], outputs: Dict[str, Any], **kwargs: Any):
        """Log the start of a chain with user input."""
        st.session_state.messages.append({"role": "assistant", "content": outputs['input']})
        st.chat_message("assistant").markdown(outputs['input'])

    def on_agent_action(self, serialized: Dict[str, Any], inputs: Dict[str, Any], **kwargs: Any):
        """Log the action taken by an agent during a chain run."""
        st.session_state.messages.append({"role": "assistant", "content": inputs['input']})
        st.chat_message("assistant").markdown(inputs['input'])

    def on_chain_end(self, outputs: Dict[str, Any], **kwargs: Any):
        """Log the end of a chain with the output generated by an agent."""
        st.session_state.messages.append({"role": self.agent_name, "content": outputs['output']})
        st.chat_message(self.agent_name).markdown(outputs['output'])

@CrewBase
class BackendCrew():
	"""BackendCrew crew"""

	@agent
	def domain(self) -> Agent:
		return Agent(
			config=self.agents_config['domain'],
			verbose=True,
		)
	
	@agent
	def configuration(self) -> Agent:
		return Agent(
			config=self.agents_config['configuration'],
			verbose=True,
		)
  
	@agent
	def dto(self) -> Agent:
		return Agent(
			config=self.agents_config['dto'],
			verbose=True,
		)
	
	@agent
	def service(self) -> Agent:
		return Agent(
			config=self.agents_config['service'],
			verbose=True,
		)

	@agent
	def commands(self) -> Agent:
		return Agent(
			config=self.agents_config['commands'],
			verbose=True,
		)
  
	@task
	def gerar_domain(self) -> Task:
		return Task(
			config=self.tasks_config['domain_task'],
   			callback=step_callback
		)
  
	@task
	def gerar_configuration(self) -> Task:
		return Task(
			config=self.tasks_config['configure_task'],
   			callback=step_callback
		)
  
	@task
	def gerar_dto(self) -> Task:
		return Task(
			config=self.tasks_config['dto_task'],
   			callback=step_callback
		)
  
	@task
	def gerar_service(self) -> Task:
		return Task(
			config=self.tasks_config['service_task'],
   			callback=step_callback
		)
  
	@task
	def gerar_commands(self) -> Task:
		return Task(
			config=self.tasks_config['command_task'],
   			callback=step_callback
		)

	@crew
	def crew(self) -> Crew:
		"""Creates the TaianeViagens crew"""
		return Crew(
			agents=self.agents, # Automatically created by the @agent decorator
			tasks=self.tasks, # Automatically created by the @task decorator
			process=Process.sequential,
			verbose=True,
			language='pt-br',
			memory=True,
			
			# process=Process.hierarchical, # In case you wanna use that instead https://docs.crewai.com/how-to/Hierarchical/
		)