
correction_task:
  description: >
    Corrija as informações de destino e origem com os códigos IATA dos aeroportos e devolva o mesmo resumo recebido, mas com a correção aplicada.
    Se atenha somente a correção dos códigos IATA dos aeroportos.
    Nunca mude o destino ou origem do usuário. Troque somente o nome do destino e origem para o IATA correto.
    Dados do usuário: {topic}
  expected_output: >
    Um resumo das informações passadas pelo usuário, com as correções aplicadas.
  agent: analista_aeroportos

buscador_passagem_task:
  description: >
    Criar um JSON e buscar as passagens disponíveis com os dados do usuário
  expected_output: >
    Um JSON com as informações de busca de passagens
  agent: buscador_passagem


agente_viagem_task:
  description: >
    Filtra as opções de passagens aéreas e apresenta as melhores opções ao usuário com base nas informações fornecidas.
    dados do usuário: {topic}
    Utilize somente os períodos de ida e volta, opção de compra (milhar ou normal) e conexões para buscar os voos.
    Utilize o JSON para fazer a chamada de API de integração.
  expected_output: >
    Quatro opções de passagens aéreas com base nas informações fornecidas.
  agent: agente_viagem
  context: 
    - buscador_passagem_task
